// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2--IvvXmb0ebJWopO_FWDvNV3fbfG_cM',
    appId: '1:279557486810:web:327ed9944322664d090de3',
    messagingSenderId: '279557486810',
    projectId: 'supplify-93798',
    authDomain: 'supplify-93798.firebaseapp.com',
    storageBucket: 'supplify-93798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw7-tWcOGgVXnaGCF7i_0Hwew6bwtEXsE',
    appId: '1:279557486810:android:ccad11a860487164090de3',
    messagingSenderId: '279557486810',
    projectId: 'supplify-93798',
    storageBucket: 'supplify-93798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZeqNFq6pz6Tu5ksEgJJAPp4YlzZmvkAk',
    appId: '1:279557486810:ios:a50261b2ae2da681090de3',
    messagingSenderId: '279557486810',
    projectId: 'supplify-93798',
    storageBucket: 'supplify-93798.firebasestorage.app',
    iosBundleId: 'com.example.supplify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZeqNFq6pz6Tu5ksEgJJAPp4YlzZmvkAk',
    appId: '1:279557486810:ios:a50261b2ae2da681090de3',
    messagingSenderId: '279557486810',
    projectId: 'supplify-93798',
    storageBucket: 'supplify-93798.firebasestorage.app',
    iosBundleId: 'com.example.supplify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2--IvvXmb0ebJWopO_FWDvNV3fbfG_cM',
    appId: '1:279557486810:web:8fc6ba84095115d7090de3',
    messagingSenderId: '279557486810',
    projectId: 'supplify-93798',
    authDomain: 'supplify-93798.firebaseapp.com',
    storageBucket: 'supplify-93798.firebasestorage.app',
  );
}



